export const FETCH_COINS_SUCCESS = 'FETCH_COINS_SUCCESS';
export const FETCH_COINS_ERROR = 'FETCH_COINS_ERROR';
export const IS_LOADING = 'IS_LOADING';

export const FETCH_COINS_HISTORY_SUCCESS = 'FETCH_COINS_HISTORY_SUCCESS';
export const FETCH_COINS_HISTORY_ERROR = 'FETCH_COINS_HISTORY_ERROR';

export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';
export const GET_LOCATION_ERROR = 'GET_LOCATION_ERROR';



